Google Summer of Code 2017
==========================
:compat-mode!:
:sectanchors:

[quote, 'http://write.flossmanuals.net/gsoc-mentoring/what-is-gsoc/[GSoC Mentoring]']
Google Summer of Code (GSoC) is a program that matches mentoring organizations with college and university student developers who are paid to write open source code.
Each year, Google works with many open source, free software and technology-related groups to identify and fund proposals for student open source projects.

Clojure has successfully participated in Google Summer of Code in 2012–2015, and we would like to do it again in 2017 as part of Clojars, a member project of the https://sfconservancy.org/[Software Freedom Conservancy].
This repository will serve as our portal for participating in GSoC 2017.
We can coordinate participation here, on the https://clojurians.slack.com/messages/gsoc/[`#gsoc` channel] in the http://clojurians.net[Clojurians slack], or on the http://groups.google.com/group/clojure[Clojure mailing list].


== Getting involved

Interested in participating in Clojars' Google Summer of Code?
Read below about how to participate.

=== Everyone

Even if you can’t participate as student or don’t want to be a mentor, you can still help by letting people know about GSoC at your local Clojure meetup, university, or other local group.


=== Students

==== Getting ready for GSoC

It’s still early in the process, but applying to be a GSoC student is very competitive.
Here are some things you can do now to improve your application:

===== Get in touch with a mentor

One of the most important things you can do to strengthen your application is to communicate with potential mentors.
A mentor can help you by reviewing your project ideas and giving you suggestions on how to improve your application.
Additionally, when selecting students, students who already having good working relationships with mentors will be in much stronger positions.

===== Get involved with the community

Talk about your idea on the http://groups.google.com/group/clojure[Clojure mailing list] or the appropriate channels in the http://clojurians.net[Clojurians slack].
These are great places to get feedback on your idea and find potential mentors.
If you will be needing to interact with one or more existing projects, get involved on those projects’ mailing lists and talk to the people involved with those projects.
All of these things will raise awareness of you and your project making it more likely that you will be able to find a good mentor.

===== Research your project

A good application will show that the you have taken the time to understand the project you would like to work on over the summer.
This includes being able to point out what are the prerequisites for your project (i.e. specific skills needed to be able to complete the project) and how you meet them.
Also, you should be able to point out possible trouble spots for your project and how you plan to mitigate those risks.

===== Show initiative

Good GSoC students are self-motivated, manage their work independently, and handle difficulties as they arise.


==== Resources

For more information about succeeding as a student, check out the http://write.flossmanuals.net/gsocstudentguide/what-is-google-summer-of-code/[GSoC Student Guide] as well as the <<general-resources,general resources>> below.


=== Mentors

[quote, 'http://write.flossmanuals.net/gsoc-mentoring/what-is-gsoc/[GSoC Mentoring]']
Mentors are people from the community who volunteer to work with a student.
Mentors provide guidance such as pointers to useful documentation, code reviews, etc.
In addition to providing students with feedback and pointers, a mentor acts as an ambassador to help student contributors integrate into their project’s community.

Becoming a mentor can be a fun and rewarding experience.
It is also a great way to help grow the community around your particular Clojure project.
You can get started now by posting suggestions for student projects on the Project Ideas page.

==== Responsibilities

To be a successful mentor, you will need to:

* Keep in touch with your student
* Take the time to review your student’s work
* Report on your student’s progress at the mid-term and the final.
  You should be able to fail your student if he or she is not performing.

A mentor does not need to micromanage a student.

==== Resources

For more information about being a great mentor check out http://write.flossmanuals.net/gsoc-mentoring/about-this-manual/[GSoC Mentoring] as well as the <<general-resources,general resources>> below.


=== Administrators

[quote, 'http://write.flossmanuals.net/gsoc-mentoring/what-is-gsoc/[GSoC Mentoring]']
Org admins are the “cat herders” for GSoC open source projects.
These people submit the organization’s application to participate in the program to Google, ensure that mentors fill out evaluations in a timely fashion, and generally organize their project’s participation in GSoC. 

Administrators help oversee the progress of the organisation and act as a point of contact for Google.
Additionally, they help ensure that mentors and students get all of the help they need.
They can also help communicate about the programme to the community.

== Project ideas

[[general-resources]]
== Resources

=== Official Google Summer of Code resources

* https://summerofcode.withgoogle.com/[Program site]
* https://developers.google.com/open-source/gsoc/faq[Official FAQ]
* https://groups.google.com/forum/#!forum/google-summer-of-code-discuss[Google Summer of Code Discuss] mailing list
* `#gsoc` on http://freenode.net/[Freenode]

=== Clojure-specific

* https://clojurians.slack.com/messages/gsoc/[`#gsoc`] in the http://clojurians.net[Clojurians slack]
